import { VitrineData, Produto } from '../types';

export const vitrineDataMock: VitrineData = {
  banner: {
    titulo: 'Fresco hoje!',
    subtitulo: 'Direto do pescador',
    descricao: 'Capturado esta manhã em Manguinhos',
    imagem: 'https://loremflickr.com/800/400/fishmonger,fish,store?seed=banner',
  },
  pescadores: [
    { id: 'pesc-001', nome: 'Sr. Antônio', foto: 'https://i.pravatar.cc/100?u=antonio' },
    { id: 'pesc-002', nome: 'D. Marlene', foto: 'https://i.pravatar.cc/100?u=marlene' },
    { id: 'pesc-003', nome: 'Seu José', foto: 'https://i.pravatar.cc/100?u=jose' },
    { id: 'pesc-004', nome: 'D. Francisca', foto: 'https://i.pravatar.cc/100?u=francisca' },
    { id: 'pesc-005', nome: 'João do Porto', foto: 'https://i.pravatar.cc/100?u=joao' },
    { id: 'pesc-006', nome: 'Maria do Mangue', foto: 'https://i.pravatar.cc/100?u=maria' },
    { id: 'pesc-007', nome: 'Seu Raimundo', foto: 'https://i.pravatar.cc/100?u=raimundo' },
    { id: 'pesc-008', nome: 'D. Luzia', foto: 'https://i.pravatar.cc/100?u=luzia' },
    { id: 'pesc-009', nome: 'Pedro Neto', foto: 'https://i.pravatar.cc/100?u=pedro' },
    { id: 'pesc-010', nome: 'Tia Jurema', foto: 'https://i.pravatar.cc/100?u=jurema' },
    { id: 'pesc-011', nome: 'Chico Barqueiro', foto: 'https://i.pravatar.cc/100?u=chico' },
    { id: 'pesc-012', nome: 'D. Neide', foto: 'https://i.pravatar.cc/100?u=neide' },
    { id: 'pesc-013', nome: 'Zé do Caranguejo', foto: 'https://i.pravatar.cc/100?u=ze' },
    { id: 'pesc-014', nome: 'Rosa Marinheira', foto: 'https://i.pravatar.cc/100?u=rosa' },
    { id: 'pesc-015', nome: 'Seu Jorge', foto: 'https://i.pravatar.cc/100?u=jorge' },
  ],
  categorias: [
    { id: 'todos', nome: 'Todos' },
    { id: 'peixe', nome: 'Peixes' },
    { id: 'crustaceo', nome: 'Crustáceos' },
  ],
  produtos: [
    {
      id: 'prod-001',
      especie: 'Robalo',
      foto: 'https://loremflickr.com/400/300/seafood?seed=robalo',
      precoPorKg: 45.0,
      pesoDisponivel: 12.5,
      categoria: 'peixe',
      badges: ['Hoje', 'Premium'],
      pescador: { id: 'pesc-001', nome: 'Sr. Antônio' },
    },
    {
      id: 'prod-002',
      especie: 'Camarão Rosa',
      foto: 'https://loremflickr.com/400/300/crab?seed=camarao',
      precoPorKg: 65.0,
      pesoDisponivel: 5.0,
      categoria: 'crustaceo',
      badges: ['Hoje', 'Favorito'],
      pescador: { id: 'pesc-002', nome: 'D. Marlene' },
    },
    {
      id: 'prod-003',
      especie: 'Tilápia',
      foto: 'https://loremflickr.com/400/300/seafood?seed=tilapia',
      precoPorKg: 32.0,
      pesoDisponivel: 20.0,
      categoria: 'peixe',
      badges: ['Premium'],
      pescador: { id: 'pesc-001', nome: 'Sr. Antônio' },
    },
    {
      id: 'prod-004',
      especie: 'Siri Mole',
      foto: 'https://loremflickr.com/400/300/crab?seed=siri',
      precoPorKg: 55.0,
      pesoDisponivel: 3.5,
      categoria: 'crustaceo',
      badges: ['Hoje'],
      pescador: { id: 'pesc-002', nome: 'D. Marlene' },
    },
    {
      id: 'prod-005',
      especie: 'Corvina',
      foto: 'https://loremflickr.com/400/300/seafood?seed=corvina',
      precoPorKg: 38.0,
      pesoDisponivel: 8.0,
      categoria: 'peixe',
      badges: [],
      pescador: { id: 'pesc-003', nome: 'Seu José' },
    },
    {
      id: 'prod-006',
      especie: 'Lagosta',
      foto: 'https://loremflickr.com/400/300/crab?seed=lagosta',
      precoPorKg: 85.0,
      pesoDisponivel: 2.0,
      categoria: 'crustaceo',
      badges: ['Premium', 'Favorito'],
      pescador: { id: 'pesc-004', nome: 'D. Francisca' },
    },
    {
      id: 'prod-007',
      especie: 'Pargo',
      foto: 'https://loremflickr.com/400/300/seafood?seed=pargo',
      precoPorKg: 42.0,
      pesoDisponivel: 6.0,
      categoria: 'peixe',
      badges: ['Hoje'],
      pescador: { id: 'pesc-005', nome: 'João do Porto' },
    },
    {
      id: 'prod-008',
      especie: 'Vermelho',
      foto: 'https://loremflickr.com/400/300/seafood?seed=vermelho',
      precoPorKg: 48.0,
      pesoDisponivel: 4.0,
      categoria: 'peixe',
      badges: [],
      pescador: { id: 'pesc-005', nome: 'João do Porto' },
    },
    {
      id: 'prod-009',
      especie: 'Sardinha',
      foto: 'https://loremflickr.com/400/300/seafood?seed=sardinha',
      precoPorKg: 18.0,
      pesoDisponivel: 30.0,
      categoria: 'peixe',
      badges: [],
      pescador: { id: 'pesc-005', nome: 'João do Porto' },
    },
    {
      id: 'prod-010',
      especie: 'Caranguejo Uçá',
      foto: 'https://loremflickr.com/400/300/crab?seed=caranguejo',
      precoPorKg: 35.0,
      pesoDisponivel: 8.0,
      categoria: 'crustaceo',
      badges: ['Hoje'],
      pescador: { id: 'pesc-006', nome: 'Maria do Mangue' },
    },
    {
      id: 'prod-011',
      especie: 'Ostra',
      foto: 'https://loremflickr.com/400/300/crab?seed=ostra',
      precoPorKg: 52.0,
      pesoDisponivel: 3.0,
      categoria: 'crustaceo',
      badges: ['Premium'],
      pescador: { id: 'pesc-006', nome: 'Maria do Mangue' },
    },
    {
      id: 'prod-012',
      especie: 'Dourado',
      foto: 'https://loremflickr.com/400/300/seafood?seed=dourado',
      precoPorKg: 40.0,
      pesoDisponivel: 7.0,
      categoria: 'peixe',
      badges: [],
      pescador: { id: 'pesc-007', nome: 'Seu Raimundo' },
    },
    {
      id: 'prod-013',
      especie: 'Anchova',
      foto: 'https://loremflickr.com/400/300/seafood?seed=anchova',
      precoPorKg: 36.0,
      pesoDisponivel: 5.5,
      categoria: 'peixe',
      badges: ['Hoje'],
      pescador: { id: 'pesc-012', nome: 'Seu Raimundo' },
    },
    {
      id: 'prod-014',
      especie: 'Lula',
      foto: 'https://loremflickr.com/400/300/crab?seed=lula',
      precoPorKg: 58.0,
      pesoDisponivel: 4.0,
      categoria: 'crustaceo',
      badges: ['Favorito'],
      pescador: { id: 'pesc-008', nome: 'D. Luzia' },
    },
    {
      id: 'prod-015',
      especie: 'Polvo',
      foto: 'https://loremflickr.com/400/300/crab?seed=polvo',
      precoPorKg: 62.0,
      pesoDisponivel: 3.0,
      categoria: 'crustaceo',
      badges: ['Premium'],
      pescador: { id: 'pesc-009', nome: 'Pedro Neto' },
    },
    {
      id: 'prod-016',
      especie: 'Tainha',
      foto: 'https://loremflickr.com/400/300/seafood?seed=tainha',
      precoPorKg: 28.0,
      pesoDisponivel: 10.0,
      categoria: 'peixe',
      badges: [],
      pescador: { id: 'pesc-010', nome: 'Tia Jurema' },
    },
  ],
};

export function gerarProdutoDetalhado(id: string): Produto | null {
  const resumo = vitrineDataMock.produtos.find(p => p.id === id);
  if (!resumo) return null;

  return {
    id: resumo.id,
    especie: resumo.especie,
    foto: resumo.foto,
    precoPorKg: resumo.precoPorKg,
    pesoDisponivel: resumo.pesoDisponivel,
    cortesDisponiveis: ['inteiro', 'limpo', 'file'],
    badges: resumo.badges,
    pescador: {
      id: resumo.pescador.id,
      nome: resumo.pescador.nome,
      foto: `https://i.pravatar.cc/150?u=${resumo.pescador.id}`,
    },
    categoria: resumo.categoria as 'peixe' | 'crustaceo',
    descricao: `${resumo.especie} fresco, direto do pescador de Manguinhos. Produto de alta qualidade.`,
  };
}
